name: CI/CD Pipeline - ML API

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: graphite-byte-472516-n8
  REGION: us-central1
  REPO_NAME: ml-repo
  IMAGE_NAME: ml-api
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  # Job 1: Testes unitários
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest tests/

  # Job 2: Build e Push Docker
  docker:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install gcloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          version: "421.0.0"

      - name: Configure Service Account and Docker
        run: |
          echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > /tmp/sa.json
          gcloud auth activate-service-account --key-file=/tmp/sa.json
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
      - name: Set Docker image version
        id: set-version
        run: echo "version=$(date +%Y.%m.%d.%H%M)" >> $GITHUB_OUTPUT

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.set-version.outputs.version }} .
          docker tag ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.set-version.outputs.version }} \
                     ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
      - name: Push Docker image
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.set-version.outputs.version }}
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest

  # Job 3: Terraform Apply (infra + deploy)
  terraform:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Decode GCP Service Account Base64 for Terraform
        run: echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > /tmp/sa.json

      - name: Terraform Init & Apply
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/sa.json
        run: |
          terraform -chdir=terraform init -backend-config="credentials=/tmp/sa.json"
          terraform -chdir=terraform apply -auto-approve -var="project=${{ env.PROJECT_ID }}" -var="region=${{ env.REGION }}" -var="image_tag=${{ needs.docker.outputs.version }}" -var="dataset_id=ml_dataset" -var="table_id=ml_table"

  # Job 4: Notificação Slack
  slack-notify:
    runs-on: ubuntu-latest
    needs: [test, docker, terraform]
    if: always()
    steps:
      - name: Send Slack notification
        run: |
          STATUS="SUCCESS"
          if [ "${{ job.status }}" != "success" ]; then
            STATUS="FAILED"
          fi
          curl -X POST -H 'Content-type: application/json' \
               --data "{\"text\":\"CI/CD Pipeline - ML API finished with status: $STATUS\"}" \
               ${{ env.SLACK_WEBHOOK }}
